name: RMM
description: Remote Management and Monitoring App


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  url_launcher: ^5.5.0
  fluttertoast: ^7.0.2
  flutter_svg: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/dashboard.svg
   - assets/notify.svg
   - assets/fb.png
   - assets/google.png
   - assets/recon.gif
   - assets/drawer.png
   - assets/textfield.svg
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Regular.ttf
        - asset: assets/Montserrat-Bold.ttf
          weight: 700

